//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRequest
    {
        public int ID { get; set; }
        public string School_Name { get; set; }
        public string Appl_Title { get; set; }
        public string Appl_Logo { get; set; }
        public string Appl_Feature { get; set; }
        public string Reference__Application { get; set; }
        public string Appl_Design { get; set; }
        public string Purpose_Project { get; set; }
        public string Details_Function_Requirment { get; set; }
        public Nullable<System.DateTime> Appli_Timeline { get; set; }
        public string City { get; set; }
        public string Target_Audience { get; set; }
        public string Application_Data { get; set; }
    }
}
