//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALayer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmahaSchoolEntities : DbContext
    {
        public EmahaSchoolEntities()
            : base("name=EmahaSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SalesUser> SalesUsers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<ClientRequest> ClientRequests { get; set; }
    }
}
